### ISSUE TITLE
ERROR in ./src/index.js Module build failed: SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by mraak** [learnrelay/learnrelay#68]
npm install went through OK, but I get this error when running it. 

Node: v6.10.3
npm: 3.10.10

```
C:\dev\projects\_testarea\pokedex\branch-step-01>npm start

> @ start C:\dev\projects\_testarea\pokedex\branch-step-01
> webpack-dev-server -d --hot --inline --history-api-fallback --no-info --port
000

http://localhost:3000/
webpack result is served from /
content is served from C:\dev\projects\_testarea\pokedex\branch-step-01
404s will fallback to /index.html
Hash: 5bcdc2717ad160cb9657
Version: webpack 1.13.1
Time: 3052ms
                           Asset       Size  Chunks             Chunk Names
    main.5bcdc2717ad160cb9657.js     284 kB       0  [emitted]  main
main.5bcdc2717ad160cb9657.js.map     310 kB       0  [emitted]  main
                      index.html  723 bytes          [emitted]
chunk    {0} main.5bcdc2717ad160cb9657.js, main.5bcdc2717ad160cb9657.js.map (ma
n) 222 kB [rendered]
    [0] multi main 52 bytes {0} [built] [1 error]
    [1] (webpack)-dev-server/client?http://localhost:3000 2.67 kB {0} [built]
    [2] (webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} [built]
    [3] (webpack)/~/node-libs-browser/~/url/~/punycode/punycode.js 14.6 kB {0}
built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] (webpack)/~/node-libs-browser/~/url/~/querystring/index.js 127 bytes {0
 [built]
    [6] (webpack)/~/node-libs-browser/~/url/~/querystring/decode.js 2.4 kB {0}
built]
    [7] (webpack)/~/node-libs-browser/~/url/~/querystring/encode.js 2.09 kB {0}
[built]
    [8] (webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] (webpack)-dev-server/~/sockjs-client/lib/transport-list.js 613 bytes {0
 [built]
   [10] (webpack)-dev-server/~/sockjs-client/lib/transport/websocket.js 2.72 kB
{0} [built]
   [11] (webpack)/~/node-libs-browser/~/process/browser.js 5.42 kB {0} [built]
   [12] (webpack)-dev-server/~/sockjs-client/lib/utils/event.js 2 kB {0} [built

   [13] (webpack)-dev-server/~/sockjs-client/lib/utils/random.js 746 bytes {0}
built]
   [14] (webpack)-dev-server/~/sockjs-client/lib/utils/browser-crypto.js 438 by
es {0} [built]
   [15] (webpack)-dev-server/~/sockjs-client/lib/utils/url.js 975 bytes {0} [bu
lt]
   [16] (webpack)-dev-server/~/sockjs-client/~/url-parse/index.js 11.4 kB {0} [
uilt]
   [17] (webpack)-dev-server/~/sockjs-client/~/url-parse/~/requires-port/index.
s 753 bytes {0} [built]
   [18] (webpack)-dev-server/~/sockjs-client/~/url-parse/~/querystringify/index
js 1.51 kB {0} [built]
   [19] (webpack)-dev-server/~/sockjs-client/~/debug/src/browser.js 4.73 kB {0}
[built]
   [20] (webpack)-dev-server/~/sockjs-client/~/debug/src/debug.js 4.39 kB {0} [
uilt]
   [21] (webpack)-dev-server/~/sockjs-client/~/debug/~/ms/index.js 2.76 kB {0}
built]
   [22] (webpack)-dev-server/~/sockjs-client/~/inherits/inherits_browser.js 672
bytes {0} [built]
   [23] (webpack)-dev-server/~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [
uilt]
   [24] (webpack)-dev-server/~/sockjs-client/lib/event/eventtarget.js 1.85 kB {
} [built]
   [25] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/websocket.js
210 bytes {0} [built]
   [26] (webpack)-dev-server/~/sockjs-client/lib/transport/xhr-streaming.js 1.2
 kB {0} [built]
   [27] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/ajax-based.js 1.
1 kB {0} [built]
   [28] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/sender-receiver.
s 1.18 kB {0} [built]
   [29] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/buffered-sender.
s 2.3 kB {0} [built]
   [30] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/polling.js 1.32
B {0} [built]
   [31] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/xhr.js 1.58
kB {0} [built]
   [32] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-cors.js 3
3 bytes {0} [built]
   [33] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/abstract-xhr
js 4.8 kB {0} [built]
   [34] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-local.js
52 bytes {0} [built]
   [35] (webpack)-dev-server/~/sockjs-client/lib/utils/browser.js 560 bytes {0}
[built]
   [36] (webpack)-dev-server/~/sockjs-client/lib/transport/xdr-streaming.js 984
bytes {0} [built]
   [37] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xdr.js 2.46 k
 {0} [built]
   [38] (webpack)-dev-server/~/sockjs-client/lib/transport/eventsource.js 766 b
tes {0} [built]
   [39] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/eventsource
js 1.58 kB {0} [built]
   [40] (webpack)-dev-server/~/sockjs-client/lib/transport/browser/eventsource.
s 37 bytes {0} [built]
   [41] (webpack)-dev-server/~/sockjs-client/lib/transport/lib/iframe-wrap.js 9
1 bytes {0} [built]
   [42] (webpack)-dev-server/~/sockjs-client/lib/transport/iframe.js 3.83 kB {0
 [built]
   [43] (webpack)-dev-server/~/sockjs-client/~/json3/lib/json3.js 43.3 kB {0} [
uilt]
   [44] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [45] (webpack)-dev-server/~/sockjs-client/lib/version.js 26 bytes {0} [built

   [46] (webpack)-dev-server/~/sockjs-client/lib/utils/iframe.js 5.03 kB {0} [b
ilt]
   [47] (webpack)-dev-server/~/sockjs-client/lib/utils/object.js 532 bytes {0}
built]
   [48] (webpack)-dev-server/~/sockjs-client/lib/transport/htmlfile.js 710 byte
 {0} [built]
   [49] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/htmlfile.js
2.2 kB {0} [built]
   [50] (webpack)-dev-server/~/sockjs-client/lib/transport/xhr-polling.js 894 b
tes {0} [built]
   [51] (webpack)-dev-server/~/sockjs-client/lib/transport/xdr-polling.js 712 b
tes {0} [built]
   [52] (webpack)-dev-server/~/sockjs-client/lib/transport/jsonp-polling.js 1.0
 kB {0} [built]
   [53] (webpack)-dev-server/~/sockjs-client/lib/transport/receiver/jsonp.js 5.
7 kB {0} [built]
   [54] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/jsonp.js 2.46
kB {0} [built]
   [55] (webpack)-dev-server/~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [56] (webpack)-dev-server/~/sockjs-client/lib/shims.js 17.2 kB {0} [built]
   [57] (webpack)-dev-server/~/sockjs-client/lib/utils/escape.js 2.36 kB {0} [b
ilt]
   [58] (webpack)-dev-server/~/sockjs-client/lib/utils/transport.js 1.35 kB {0}
[built]
   [59] (webpack)-dev-server/~/sockjs-client/lib/utils/log.js 450 bytes {0} [bu
lt]
   [60] (webpack)-dev-server/~/sockjs-client/lib/event/event.js 477 bytes {0} [
uilt]
   [61] (webpack)-dev-server/~/sockjs-client/lib/location.js 177 bytes {0} [bui
t]
   [62] (webpack)-dev-server/~/sockjs-client/lib/event/close.js 295 bytes {0} [
uilt]
   [63] (webpack)-dev-server/~/sockjs-client/lib/event/trans-message.js 292 byt
s {0} [built]
   [64] (webpack)-dev-server/~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [
uilt]
   [65] (webpack)-dev-server/~/sockjs-client/lib/transport/sender/xhr-fake.js 4
6 bytes {0} [built]
   [66] (webpack)-dev-server/~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [bu
lt]
   [67] (webpack)-dev-server/~/sockjs-client/lib/info-iframe-receiver.js 791 by
es {0} [built]
   [68] (webpack)-dev-server/~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [buil
]
   [69] (webpack)-dev-server/~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0}
[built]
   [70] (webpack)-dev-server/~/sockjs-client/lib/facade.js 723 bytes {0} [built

   [71] (webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [72] (webpack)-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes {0} [
uilt]
   [73] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
   [74] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dev\projects\_testarea\pokedex\branch-step-01\nod
_modules\babel-plugin-react-relay\lib\index.js:42:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\dev\projects\_testarea\pokedex\branch-step-01\node_modules\babel-core
lib\transformation\file\options\option-manager.js:178:20
    at Array.map (native)
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./index.html 1.08 kB {0} [bui
t]
        [1] ./~/html-webpack-plugin/~/lodash/lodash.js 540 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
```

**Comment by mraak** [comment]
Deleting node_modules and reinstalling them solved the problem.
