### ISSUE TITLE
Module build failed: FetchError: request failed, reason: socket hang up

### ISSUE THREAD

**Issue by mraak** [learnrelay/learnrelay#70]
Windows 7, Node v6.10.3. I'm using endpoint that is given in the tutorial, which works inside the browser GraphiQL on tutorial page . Also when I try connecting to my endpoint that I developed on a whole different app, it works. So it's neither the backend nor the frontend?! Weird.

C:\dev\projects\_testarea\pokedex\branch-step-01>
C:\dev\projects\_testarea\pokedex\branch-step-01>npm start

> @ start C:\dev\projects\_testarea\pokedex\branch-step-01
> webpack-dev-server -d --hot --inline --history-api-fallback --no-info --port 3
000

http://localhost:3000/
webpack result is served from /
content is served from C:\dev\projects\_testarea\pokedex\branch-step-01
404s will fallback to /index.html
Hash: b4e690f005060bdbb4de
Version: webpack 1.13.1
Time: 1956ms
                           Asset       Size  Chunks             Chunk Names
    main.b4e690f005060bdbb4de.js     279 kB       0  [emitted]  main
main.b4e690f005060bdbb4de.js.map     307 kB       0  [emitted]  main
                      index.html  723 bytes          [emitted]
chunk    {0} main.b4e690f005060bdbb4de.js, main.b4e690f005060bdbb4de.js.map (mai
n) 222 kB [rendered]
    [0] multi main 52 bytes {0} [built] [1 error]
    [1] (webpack)-dev-server/client?http://localhost:3000 2.67 kB {0} [built]
    [2] ./~/url/url.js 22.3 kB {0} [built]
    [3] ./~/url/~/punycode/punycode.js 14.6 kB {0} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} [built]
    [5] ./~/querystring/index.js 127 bytes {0} [built]
    [6] ./~/querystring/decode.js 2.4 kB {0} [built]
    [7] ./~/querystring/encode.js 2.09 kB {0} [built]
    [8] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
    [9] ./~/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
   [10] ./~/sockjs-client/lib/transport/websocket.js 2.72 kB {0} [built]
   [11] ./~/process/browser.js 5.42 kB {0} [built]
   [12] ./~/sockjs-client/lib/utils/event.js 2 kB {0} [built]
   [13] ./~/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
   [14] ./~/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
   [15] ./~/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
   [16] ./~/url-parse/index.js 11.4 kB {0} [built]
   [17] ./~/requires-port/index.js 753 bytes {0} [built]
   [18] ./~/url-parse/~/querystringify/index.js 1.51 kB {0} [built]
   [19] ./~/debug/src/browser.js 4.73 kB {0} [built]
   [20] ./~/debug/src/debug.js 4.39 kB {0} [built]
   [21] ./~/ms/index.js 2.76 kB {0} [built]
   [22] ./~/inherits/inherits_browser.js 672 bytes {0} [built]
   [23] ./~/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
   [24] ./~/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
   [25] ./~/sockjs-client/lib/transport/browser/websocket.js 210 bytes {0} [buil
t]
   [26] ./~/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
   [27] ./~/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
   [28] ./~/sockjs-client/lib/transport/lib/sender-receiver.js 1.18 kB {0} [buil
t]
   [29] ./~/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built
]
   [30] ./~/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
   [31] ./~/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
   [32] ./~/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]

   [33] ./~/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [buil
t]
   [34] ./~/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built
]
   [35] ./~/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
   [36] ./~/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
   [37] ./~/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
   [38] ./~/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
   [39] ./~/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [bui
lt]
   [40] ./~/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [bui
lt]
   [41] ./~/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]

   [42] ./~/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
   [43] ./~/json3/lib/json3.js 43.3 kB {0} [built]
   [44] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
   [45] ./~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [46] ./~/sockjs-client/lib/utils/iframe.js 5.03 kB {0} [built]
   [47] ./~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [48] ./~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [49] ./~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [50] ./~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [51] ./~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [52] ./~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [53] ./~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [54] ./~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [55] ./~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [56] ./~/sockjs-client/lib/shims.js 17.2 kB {0} [built]
   [57] ./~/sockjs-client/lib/utils/escape.js 2.36 kB {0} [built]
   [58] ./~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [59] ./~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [60] ./~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [61] ./~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [62] ./~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [63] ./~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [64] ./~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [65] ./~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]

   [66] ./~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [67] ./~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [68] ./~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [69] ./~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [70] ./~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [71] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [72] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [73] (webpack)/hot/dev-server.js 1.85 kB {0} [built]
   [74] (webpack)/hot/log-apply-result.js 813 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: FetchError: request to https://api.graph.cool/relay/v1/cj5d
zxtpowxqg0122konmn5ve failed, reason: socket hang up
    at ClientRequest.<anonymous> (C:\dev\projects\_testarea\pokedex\branch-step-
01\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketCloseListener (_http_client.js:285:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
    at module.exports.loopWhile (C:\dev\projects\_testarea\pokedex\branch-step-0
1\node_modules\deasync\index.js:72:22)
    at exports.default (C:\dev\projects\_testarea\pokedex\branch-step-01\node_mo
dules\babel-plugin-react-relay\lib\index.js:21:26)
    at Function.memoisePluginContainer (C:\dev\projects\_testarea\pokedex\branch
-step-01\node_modules\babel-core\lib\transformation\file\options\option-manager.
js:113:13)
    at Function.normalisePlugin (C:\dev\projects\_testarea\pokedex\branch-step-0
1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:
32)
    at C:\dev\projects\_testarea\pokedex\branch-step-01\node_modules\babel-core\
lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (C:\dev\projects\_testarea\pokedex\branch-step-
01\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158
:20)
    at OptionManager.mergeOptions (C:\dev\projects\_testarea\pokedex\branch-step
-01\node_modules\babel-core\lib\transformation\file\options\option-manager.js:23
4:36)
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./index.html 1.04 kB {0} [buil
t]
        [1] ./~/lodash/lodash.js 540 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
Hash: b4e690f005060bdbb4de
Version: webpack 1.13.1
Time: 601ms
chunk    {0} main.b4e690f005060bdbb4de.js, main.b4e690f005060bdbb4de.js.map (mai
n) 222 kB
     + 75 hidden modules

ERROR in ./src/index.js
Module build failed: FetchError: request to https://api.graph.cool/relay/v1/cj5d
zxtpowxqg0122konmn5ve failed, reason: socket hang up
    at ClientRequest.<anonymous> (C:\dev\projects\_testarea\pokedex\branch-step-
01\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketCloseListener (_http_client.js:285:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
    at module.exports.loopWhile (C:\dev\projects\_testarea\pokedex\branch-step-0
1\node_modules\deasync\index.js:72:22)
    at exports.default (C:\dev\projects\_testarea\pokedex\branch-step-01\node_mo
dules\babel-plugin-react-relay\lib\index.js:21:26)
    at Function.memoisePluginContainer (C:\dev\projects\_testarea\pokedex\branch
-step-01\node_modules\babel-core\lib\transformation\file\options\option-manager.
js:113:13)
    at Function.normalisePlugin (C:\dev\projects\_testarea\pokedex\branch-step-0
1\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:
32)
    at C:\dev\projects\_testarea\pokedex\branch-step-01\node_modules\babel-core\
lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (C:\dev\projects\_testarea\pokedex\branch-step-
01\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158
:20)
    at OptionManager.mergeOptions (C:\dev\projects\_testarea\pokedex\branch-step
-01\node_modules\babel-core\lib\transformation\file\options\option-manager.js:23
4:36)
 @ multi main
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB
         + 3 hidden modules
Terminate batch job (Y/N)? y

**Comment by marktani** [comment]
> https://api.graph.cool/relay/v1/cj5d zxtpowxqg0122konmn5ve

There seems to be a space in your endpoint URL, is that correct?

**Comment by mraak** [comment]
No, that's just bad copy from Windows command line. This is step-01 branch. btw.

**Comment by marktani** [comment]
Could you try again? I don't see a reason the endpoint is not reachable, because I can make queries directly

**Comment by mraak** [comment]
I tried multiple times. I can also make queries from the lesson page's graphiql. But when I run npm start I get the above in step-01. I haven't tried other branches yet. For now I'm playing with my own end point on localhost.

**Comment by mraak** [comment]
Same happens on step-03 branch.

**Comment by marktani** [comment]
So this doesn't happen on step-02?
